WITH RECURSIVE cte
AS (
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION
    SELECT ECOLI_DATA.ID, ECOLI_DATA.PARENT_ID, GEN + 1
    FROM cte INNER JOIN ECOLI_DATA
    ON cte.ID = ECOLI_DATA.PARENT_ID
)

SELECT ID
FROM cte
WHERE GEN = 3
ORDER BY ID