SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID NOT IN (
    SELECT PARENT_ITEM_ID
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NOT NULL -- NULL이 포함되면 ITEM_ID NOT IN (NULL)이 항상 False
)
ORDER BY ITEM_ID DESC;