-- 코드를 입력하세요
SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(*) >= 2
ORDER BY USER_ID, PRODUCT_ID DESC;

# JOIN 방식
# SELECT DISTINCT o1.USER_ID, o1.PRODUCT_ID
# FROM ONLINE_SALE o1
# JOIN ONLINE_SALE o2 
#   ON o1.USER_ID = o2.USER_ID 
#  AND o1.PRODUCT_ID = o2.PRODUCT_ID
#  AND o1.ONLINE_SALE_ID <> o2.ONLINE_SALE_ID   -- 자기 자신은 제외
# ORDER BY o1.USER_ID, o1.PRODUCT_ID DESC;