SELECT ID, (
    CASE
        WHEN RK / CNT * 100 <= 25 THEN 'CRITICAL'
        WHEN RK / CNT * 100 <= 50 THEN 'HIGH'
        WHEN RK / CNT * 100 <= 75 THEN 'MEDIUM'
        WHEN RK / CNT * 100 <= 100 THEN 'LOW'
    END
    ) AS COLONY_NAME
FROM (
    SELECT 
        ID,
        RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS RK,
        COUNT(*) OVER() AS CNT
    FROM ECOLI_DATA
    ORDER BY SIZE_OF_COLONY
) T
ORDER BY ID
