# SELECT f.PRODUCT_ID, f.PRODUCT_NAME, f.PRODUCT_CD, f.CATEGORY, f.PRICE
# FROM FOOD_PRODUCT f
# JOIN (
#     SELECT MAX(PRICE) PRICE
#     FROM FOOD_PRODUCT
# ) t
# ON f.PRICE = t.PRICE;

SELECT *
FROM FOOD_PRODUCT
WHERE PRICE = (
    SELECT MAX(PRICE)
    FROM FOOD_PRODUCT
);