SET @total = (
    SELECT COUNT(USER_ID)
    FROM USER_INFO
    WHERE JOINED LIKE '2021%'
);

SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    # 해당 년, 월에 상품을 구입한 사용자의 수 -> 중복 X
    COUNT(DISTINCT(USER_ID)) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT(USER_ID)) / @total, 1) AS PUCHASED_RATIO
FROM ONLINE_SALE S
JOIN USER_INFO U USING (USER_ID)
WHERE YEAR(JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY 1, 2