WITH RECURSIVE PARENT(ID, PARENT_ID, GEN)
AS (
    SELECT ID, PARENT_ID, 1
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION
    SELECT E.ID, E.PARENT_ID, GEN + 1
    FROM PARENT P JOIN ECOLI_DATA E
    ON P.ID = E.PARENT_ID
)

SELECT COUNT(1) AS COUNT, GEN AS GENERATION
FROM PARENT
WHERE ID NOT IN (SELECT PARENT_ID FROM PARENT WHERE PARENT_ID iS NOT NULL)
GROUP BY 2
ORDER BY 2