WITH RECURSIVE PARENT
AS (
    SELECT ID, PARENT_ID, 0 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E.ID, E.PARENT_ID, GEN + 1
    FROM PARENT P LEFT OUTER JOIN ECOLI_DATA E
    ON P.ID = E.PARENT_ID
    WHERE P.ID IS NOT NULL
)

SELECT COUNT(1) AS COUNT, GEN AS GENERATION
FROM PARENT
WHERE ID IS NULL
GROUP BY ID, GEN
ORDER BY GEN