WITH t AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
) -- 대여중인 자동차

SELECT DISTINCT a.CAR_ID,
        CASE
            WHEN t.CAR_ID IS NOT NULL THEN '대여중'
            ELSE '대여 가능'
        END AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY a
LEFT JOIN t
ON a.CAR_ID = t.CAR_ID
ORDER BY 1 DESC;