WITH t AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-10-16' AND '2022-10-16' <= END_DATE
) -- 대여중

SELECT DISTINCT a.CAR_ID,
        CASE
            WHEN t.CAR_ID IS NOT NULL THEN '대여중'
            ELSE '대여 가능'
        END AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY a
LEFT JOIN t
ON a.CAR_ID = t.CAR_ID
ORDER BY 1 DESC;
