-- 코드를 작성해주세요
SELECT CASE 
        WHEN 1 <= MONTH(DIFFERENTIATION_DATE) && MONTH(DIFFERENTIATION_DATE) < 4 THEN '1Q'
        WHEN 4 <= MONTH(DIFFERENTIATION_DATE) && MONTH(DIFFERENTIATION_DATE) < 7 THEN '2Q'
        WHEN 7 <= MONTH(DIFFERENTIATION_DATE) && MONTH(DIFFERENTIATION_DATE) < 10 THEN '3Q'
        ELSE '4Q'
        END QUARTER,
    COUNT(*) ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY 1
ORDER BY 1;