WITH RECURSIVE cte
AS (
    SELECT 0 AS N
    UNION ALL
    SELECT N + 1
    FROM cte
    WHERE N < 23
)

SELECT cte.N, IFNULL(COUNT, 0) AS COUNT
FROM (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(1) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY 1
) t RIGHT JOIN cte ON t.HOUR = cte.N
ORDER BY 1