WITH RECURSIVE cte
AS (
    SELECT 0 AS N
    UNION ALL
    SELECT N + 1
    FROM cte
    WHERE N < 23
)

SELECT cte.N, SUM(if(cte.n = HOUR(DATETIME), 1, 0)) COUNT
FROM cte, ANIMAL_OUTS
GROUP BY 1
ORDER BY 1