SELECT EMP_NO, EMP_NAME, GRADE, 
(CASE
    WHEN GRADE = 'S' THEN SAL * 0.2
    WHEN GRADE = 'A' THEN SAL * 0.15
    WHEN GRADE = 'B' THEN SAL * 0.1
    ELSE 0
END) AS BONUS
FROM (
    SELECT EMP_NO, EMP_NAME, SAL,
        (CASE
            WHEN AVG(SCORE) >= 96 THEN 'S'
            WHEN AVG(SCORE) >= 90 THEN 'A'
            WHEN AVG(SCORE) >= 80 THEN 'B'
            ELSE 'C'
        END) AS GRADE
    FROM HR_EMPLOYEES
    JOIN HR_GRADE USING (EMP_NO)
    GROUP BY EMP_NO
) t 
ORDER BY 1
