SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM (
        SELECT MEMBER_ID, MEMBER_NAME, COUNT(1) AS CNT
        FROM MEMBER_PROFILE
        JOIN REST_REVIEW USING (MEMBER_ID)
        GROUP BY MEMBER_ID
        ORDER BY CNT DESC
        LIMIT 1
    ) T
JOIN REST_REVIEW USING (MEMBER_ID)
ORDER BY 3, 2