SELECT MEMBER_NAME, REVIEW_TEXT, REVIEW_DATE
FROM MEMBER_PROFILE
JOIN REST_REVIEW USING (MEMBER_ID)
JOIN (
    SELECT
        MEMBER_ID,
        COUNT(1) AS TOTAL
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY TOTAL DESC
    LIMIT 1
) T USING(MEMBER_ID)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC

