-- 코드를 작성해주세요
SELECT c.ITEM_ID, c.ITEM_NAME, c.RARITY
FROM ITEM_TREE t
JOIN ITEM_INFO c ON c.ITEM_ID = t.ITEM_ID            -- 자식
JOIN ITEM_INFO p ON p.ITEM_ID = t.PARENT_ITEM_ID     -- 부모
WHERE p.RARITY = 'RARE'
ORDER BY ITEM_ID DESC;