# SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(1) AS RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) BETWEEN 8 AND 10 
# GROUP BY MONTH(START_DATE), CAR_ID
# HAVING RECORDS > 0
# ORDER BY 1, 2 DESC

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(1) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE YEAR(START_DATE) = 2022
  AND MONTH(START_DATE) BETWEEN 8 AND 10
  AND CAR_ID IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) BETWEEN 8 AND 10
        GROUP BY 1
        HAVING COUNT(1) >= 5
    )
GROUP BY MONTH(START_DATE), CAR_ID
HAVING RECORDS > 0
ORDER BY 1, 2 DESC