SELECT t.YEAR, t.MAX_SIZE - e.SIZE_OF_COLONY YEAR_DEV, e.ID
FROM ECOLI_DATA e
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) YEAR, SIZE_OF_COLONY MAX_SIZE, ROW_NUMBER() OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE) ORDER BY SIZE_OF_COLONY DESC) RN
    FROM ECOLI_DATA
) t
ON YEAR(e.DIFFERENTIATION_DATE) = t.YEAR AND t.RN = 1
ORDER BY 1, 2;