SELECT a.ID, b.FISH_NAME, a.LENGTH
FROM (
    SELECT ID, FISH_TYPE, LENGTH, ROW_NUMBER() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) RN
    FROM FISH_INFO
) a
JOIN FISH_NAME_INFO b
ON a.FISH_TYPE = b.FISH_TYPE AND a.RN = 1
ORDER BY 1;