SELECT ID, FISH_NAME, LENGTH
FROM (
    SELECT ID, FISH_NAME, LENGTH
    , RANK() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS RK
    FROM FISH_INFO
    JOIN FISH_NAME_INFO USING (FISH_TYPE)
) T
WHERE RK = 1
ORDER BY 1