SELECT
(CASE
    WHEN SKILL_CODE & (
        SELECT CODE FROM SKILLCODES WHERE NAME = 'Python'
        )
        AND
        SKILL_CODE & (
            SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End'
        ) THEN 'A'
    WHEN SKILL_CODE & (
        SELECT CODE
        FROM SKILLCODES
        WHERE NAME = 'C#'
    ) THEN 'B'
    WHEN EXISTS(
        SELECT CODE
        FROM SKILLCODES
        WHERE CATEGORY = "Front End" AND SKILL_CODE & CODE
    ) THEN 'C'
END) AS GRADE, ID, EMAIL
FROM DEVELOPERS
HAVING GRADE IS NOT NULL
ORDER BY 1, 2